#!/bin/sh
# this demo's cluster has its own network and 3 brokers
export KAFKA_NETWORK=rabbitmq-kafka-durable_default KAFKA_BOOTSTRAP=kafka-1:19092,kafka-2:19092,kafka-3:19092
cd "$(dirname "$0")" && exec ../../bin/kafka-php "$@"
